name: "RepoSage"
description: "AI-driven bot for repository analysis and improvement. RepoSage suggests and implements code improvements, generates tests for changes, and validates changes by running tests before committing."
author: "ktzehan"
inputs:
  github_token:
    description: "GitHub token for repository access"
    required: true
  open_router_api_key:
    description: "OpenRouter API key for AI model access"
    required: true
  repo:
    description: "Repository name (e.g., \"username/repo\"), defaults to current repo"
    required: false
    default: ${{ github.repository }}
  model:
    description: "AI model to use for analysis"
    required: false
    default: "anthropic/claude-3-opus:beta"
  base_branch:
    description: "Base branch to use for analysis"
    required: false
    default: "main"
  description:
    description: "PR description or commit message description"
    required: false
    default: "RepoSage identified these improvements for your codebase."
  dry_run:
    description: "Generate changes without creating PRs or committing directly. Useful for testing."
    required: false
    default: "false"
  output_file:
    description: "Save analysis results to a JSON file"
    required: false
    default: ""
  max_workers:
    description: "Maximum number of worker threads for parallel processing"
    required: false
    default: "4"
  use_pr:
    description: "Create pull requests instead of committing directly to the base branch"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Run RepoSage
      shell: bash
      run: |
        pip install -r repo-sage-action/requirements.txt
        python repo-sage-action/bot.py \
          --github-token ${{ inputs.github_token }} \
          --open-router-api-key ${{ inputs.open_router_api_key }} \
          --repo ${{ inputs.repo }} \
          --model ${{ inputs.model }} \
          --base-branch ${{ inputs.base_branch }} \
          ${{ inputs.description != '' && format('--description "{0}"', inputs.description) || '' }} \
          ${{ inputs.dry_run == 'true' && '--dry-run' || '' }} \
          ${{ inputs.output_file != '' && format('--output-file "{0}"', inputs.output_file) || '' }} \
          ${{ inputs.max_workers != '0' && format('--max-workers {0}', inputs.max_workers) || '' }} \
          ${{ inputs.use_pr == 'true' && '--use-pr' || '' }}
branding:
  icon: "robot"
  color: "blue"