name: "RepoSage"
description: "A bot that analyzes a repository and suggests improvements based on AI and RAG."
author: "Your Name"
inputs:
  github_token:
    description: "GitHub Token"
    required: true
  open_router_api_key:
    description: "Open Router API Key"
    required: true
  repo:
    description: "Repository to analyze (defaults to current repository)"
    required: false
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Run RepoSage
      shell: bash
      run: |
        pip install -r ./requirements.txt
        python ./bot.py --github-token ${{ inputs.github_token }} --open-router-api-key ${{ inputs.open_router_api_key }} --repo ${{ inputs.repo }}
branding:
  icon: "robot"
  color: "blue"