name: "RepoSage"
description: "A bot that analyzes a repository and suggests improvements based on AI and RAG."
author: "Your Name"
inputs:
  github_token:
    description: "GitHub Token"
    required: true
  open_router_api_key:
    description: "Open Router API Key"
    required: true
  repo:
    description: "Repository to analyze (defaults to current repository)"
    required: false
runs:
  using: "docker"
  image: "python:3.8-slim"
  args:
    - "python"
    - "./bot.py"
branding:
  icon: "robot"
  color: "blue"